export const countries = [
  { name: "Afghanistan", nativeName: "افغانستان", code: "+93", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg" },
  { name: "Albania", nativeName: "Shqipëri", code: "+355", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg" },
  { name: "Algeria", nativeName: "الجزائر", code: "+213", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg" },
  { name: "Andorra", nativeName: "Andorra", code: "+376", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg" },
  { name: "Angola", nativeName: "Angola", code: "+244", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg" },
  { name: "Argentina", nativeName: "Argentina", code: "+54", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg" },
  { name: "Armenia", nativeName: "Հայաստան", code: "+374", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg" },
  { name: "Australia", nativeName: "Australia", code: "+61", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg" },
  { name: "Austria", nativeName: "Österreich", code: "+43", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg" },
  { name: "Azerbaijan", nativeName: "Azərbaycan", code: "+994", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg" },
  { name: "Bahamas", nativeName: "Bahamas", code: "+1-242", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg" },
  { name: "Bahrain", nativeName: "البحرين", code: "+973", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg" },
  { name: "Bangladesh", nativeName: "বাংলাদেশ", code: "+880", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg" },
  { name: "Belarus", nativeName: "Беларусь", code: "+375", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg" },
  { name: "Belgium", nativeName: "België", code: "+32", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg" },
  { name: "Belize", nativeName: "Belize", code: "+501", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg" },
  { name: "Benin", nativeName: "Bénin", code: "+229", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg" },
  { name: "Bhutan", nativeName: "འབྲུག་", code: "+975", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg" },
  { name: "Bolivia", nativeName: "Bolivia", code: "+591", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg" },
  { name: "Bosnia and Herzegovina", nativeName: "Bosna i Hercegovina", code: "+387", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg" },
  { name: "Botswana", nativeName: "Botswana", code: "+267", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg" },
  { name: "Brazil", nativeName: "Brasil", code: "+55", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg" },
  { name: "Brunei", nativeName: "بروني", code: "+673", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg" },
  { name: "Bulgaria", nativeName: "България", code: "+359", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg" },
  { name: "Burkina Faso", nativeName: "Burkina Faso", code: "+226", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg" },
  { name: "Cambodia", nativeName: "កម្ពុជា", code: "+855", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg" },
  { name: "Cameroon", nativeName: "Cameroun", code: "+237", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg" },
  { name: "Canada", nativeName: "Canada", code: "+1", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg" },
  { name: "China", nativeName: "中国", code: "+86", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg" },
  { name: "Colombia", nativeName: "Colombia", code: "+57", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg" },
  { name: "Croatia", nativeName: "Hrvatska", code: "+385", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg" },
  { name: "Cuba", nativeName: "Cuba", code: "+53", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg" },
  { name: "Cyprus", nativeName: "Κύπρος", code: "+357", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg" },
  { name: "Czech Republic", nativeName: "Česko", code: "+420", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg" },
  { name: "Denmark", nativeName: "Danmark", code: "+45", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg" },
  { name: "Dominican Republic", nativeName: "República Dominicana", code: "+1-809", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg" },
  { name: "Egypt", nativeName: "مصر", code: "+20", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg" },
  { name: "El Salvador", nativeName: "El Salvador", code: "+503", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg" },
  { name: "Equatorial Guinea", nativeName: "Guinea Ecuatorial", code: "+240", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg" },
  { name: "Eritrea", nativeName: "ኤርትራ", code: "+291", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg" },
  { name: "Estonia", nativeName: "Eesti", code: "+372", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg" },
  { name: "Eswatini", nativeName: "Eswatini", code: "+268", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg" },
  { name: "Ethiopia", nativeName: "ኢትዮጵያ", code: "+251", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg" },
  { name: "Fiji", nativeName: "Fiji", code: "+679", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg" },
  { name: "Finland", nativeName: "Suomi", code: "+358", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg" },
  { name: "France", nativeName: "France", code: "+33", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg" },
  { name: "Gabon", nativeName: "Gabon", code: "+241", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg" },
  { name: "Gambia", nativeName: "Gambia", code: "+220", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg" },
  { name: "Georgia", nativeName: "საქართველო", code: "+995", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg" },
  { name: "Germany", nativeName: "Deutschland", code: "+49", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg" },
  { name: "Ghana", nativeName: "Ghana", code: "+233", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg" },
  { name: "Greece", nativeName: "Ελλάδα", code: "+30", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg" },
  { name: "Grenada", nativeName: "Grenada", code: "+1-473", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg" },
  { name: "Guatemala", nativeName: "Guatemala", code: "+502", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg" },
  { name: "Guinea", nativeName: "Guinée", code: "+224", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg" },
  { name: "Guinea-Bissau", nativeName: "Guiné-Bissau", code: "+245", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg" },
  { name: "Guyana", nativeName: "Guyana", code: "+592", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg" },
  { name: "Haiti", nativeName: "Haïti", code: "+509", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg" },
  { name: "Honduras", nativeName: "Honduras", code: "+504", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg" },
  { name: "Hungary", nativeName: "Magyarország", code: "+36", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg" },
  { name: "Iceland", nativeName: "Ísland", code: "+354", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg" },
  { name: "India", nativeName: "भारत", code: "+91", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg" },
  { name: "Indonesia", nativeName: "Indonesia", code: "+62", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg" },
  { name: "Iran", nativeName: "ایران", code: "+98", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg" },
  { name: "Iraq", nativeName: "العراق", code: "+964", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg" },
  { name: "Ireland", nativeName: "Éire", code: "+353", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg" },
 { name: "Italy", nativeName: "Italia", code: "+39", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg" },
  { name: "Jamaica", nativeName: "Jamaica", code: "+1-876", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg" },
  { name: "Japan", nativeName: "日本", code: "+81", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg" },
  { name: "Jordan", nativeName: "الأردن", code: "+962", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg" },
  { name: "Kazakhstan", nativeName: "Қазақстан", code: "+7", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg" },
  { name: "Kenya", nativeName: "Kenya", code: "+254", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg" },
  { name: "Kiribati", nativeName: "Kiribati", code: "+686", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg" },
  { name: "Korea, North", nativeName: "조선 민주주의 인민 공화국", code: "+850", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg" },
  { name: "Korea, South", nativeName: "대한민국", code: "+82", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg" },
  { name: "Kuwait", nativeName: "الكويت", code: "+965", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg" },
  { name: "Kyrgyzstan", nativeName: "Кыргызстан", code: "+996", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg" },
  { name: "Laos", nativeName: "ລາວ", code: "+856", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg" },
  { name: "Latvia", nativeName: "Latvija", code: "+371", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg" },
  { name: "Lebanon", nativeName: "لبنان", code: "+961", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg" },
  { name: "Lesotho", nativeName: "Lesotho", code: "+266", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg" },
  { name: "Liberia", nativeName: "Liberia", code: "+231", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg" },
  { name: "Libya", nativeName: "ليبيا", code: "+218", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg" },
  { name: "Liechtenstein", nativeName: "Liechtenstein", code: "+423", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg" },
  { name: "Lithuania", nativeName: "Lietuva", code: "+370", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg" },
  { name: "Luxembourg", nativeName: "Luxembourg", code: "+352", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg" },
  { name: "Madagascar", nativeName: "Madagasikara", code: "+261", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg" },
  { name: "Malawi", nativeName: "Malawi", code: "+265", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg" },
  { name: "Malaysia", nativeName: "Malaysia", code: "+60", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg" },
  { name: "Maldives", nativeName: "Maldives", code: "+960", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg" },
  { name: "Mali", nativeName: "Mali", code: "+223", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg" },
  { name: "Malta", nativeName: "Malta", code: "+356", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg" },
  { name: "Marshall Islands", nativeName: "Marshall Islands", code: "+692", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg" },
  { name: "Mauritania", nativeName: "موريتانيا", code: "+222", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg" },
  { name: "Mauritius", nativeName: "Mauritius", code: "+230", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg" },
  { name: "Mexico", nativeName: "México", code: "+52", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg" },
  { name: "Micronesia", nativeName: "Federated States of Micronesia", code: "+691", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg" },
  { name: "Moldova", nativeName: "Moldova", code: "+373", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg" },
  { name: "Monaco", nativeName: "Monaco", code: "+377", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg" },
  { name: "Mongolia", nativeName: "Монгол", code: "+976", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg" },
  { name: "Montenegro", nativeName: "Crna Gora", code: "+382", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg" },
  { name: "Morocco", nativeName: "المغرب", code: "+212", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg" },
  { name: "Mozambique", nativeName: "Moçambique", code: "+258", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg" },
  { name: "Myanmar", nativeName: "မြန်မာ", code: "+95", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg" },
  { name: "Namibia", nativeName: "Namibia", code: "+264", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg" },
  { name: "Nauru", nativeName: "Nauru", code: "+674", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg" },
  { name: "Nepal", nativeName: "नेपाल", code: "+977", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg" },
  { name: "Netherlands", nativeName: "Nederland", code: "+31", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg" },
  { name: "New Zealand", nativeName: "New Zealand", code: "+64", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg" },
  { name: "Nicaragua", nativeName: "Nicaragua", code: "+505", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg" },
  { name: "Niger", nativeName: "Niger", code: "+227", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg" },
  { name: "Nigeria", nativeName: "Nigeria", code: "+234", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg" },
  { name: "North Macedonia", nativeName: "Северна Македонија", code: "+389", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg" },
  { name: "Norway", nativeName: "Norge", code: "+47", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg" },
  { name: "Oman", nativeName: "عمان", code: "+968", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg" },
  { name: "Pakistan", nativeName: "پاکستان", code: "+92", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg" },
  { name: "Palau", nativeName: "Palau", code: "+680", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg" },
  { name: "Panama", nativeName: "Panamá", code: "+507", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg" },
  { name: "Papua New Guinea", nativeName: "Papua New Guinea", code: "+675", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg" },
  { name: "Paraguay", nativeName: "Paraguay", code: "+595", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg" },
  { name: "Peru", nativeName: "Perú", code: "+51", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg" },
  { name: "Philippines", nativeName: "Pilipinas", code: "+63", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg" },
  { name: "Poland", nativeName: "Polska", code: "+48", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg" },
  { name: "Portugal", nativeName: "Portugal", code: "+351", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg" },
  { name: "Qatar", nativeName: "قطر", code: "+974", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg" },
  { name: "Romania", nativeName: "România", code: "+40", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg" },
  { name: "Russia", nativeName: "Россия", code: "+7", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg" },
  { name: "Rwanda", nativeName: "Rwanda", code: "+250", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg" },
  { name: "Saint Kitts and Nevis", nativeName: "Saint Kitts and Nevis", code: "+1-869", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg" },
  { name: "Saint Lucia", nativeName: "Saint Lucia", code: "+1-758", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg" },
  { name: "Saint Vincent and the Grenadines", nativeName: "Saint Vincent and the Grenadines", code: "+1-784", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg" },
  { name: "Samoa", nativeName: "Samoa", code: "+685", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg" },
  { name: "San Marino", nativeName: "San Marino", code: "+378", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg" },
  { name: "Sao Tome and Principe", nativeName: "São Tomé and Príncipe", code: "+239", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg" },
  { name: "Saudi Arabia", nativeName: "المملكة العربية السعودية", code: "+966", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg" },
  { name: "Senegal", nativeName: "Sénégal", code: "+221", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg" },
  { name: "Serbia", nativeName: "Србија", code: "+381", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg" },
  { name: "Seychelles", nativeName: "Seychelles", code: "+248", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg" },
  { name: "Sierra Leone", nativeName: "Sierra Leone", code: "+232", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg" },
  { name: "Singapore", nativeName: "Singapore", code: "+65", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg" },
  { name: "Slovakia", nativeName: "Slovensko", code: "+421", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg" },
  { name: "Slovenia", nativeName: "Slovenija", code: "+386", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg" },
  { name: "Solomon Islands", nativeName: "Solomon Islands", code: "+677", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg" },
  { name: "Somalia", nativeName: "Soomaaliya", code: "+252", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg" },
  { name: "South Africa", nativeName: "South Africa", code: "+27", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg" },
  { name: "South Sudan", nativeName: "جنوب السودان", code: "+211", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg" },
  { name: "Spain", nativeName: "España", code: "+34", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg" },
  { name: "Sri Lanka", nativeName: "ශ්‍රී ලංකා", code: "+94", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg" },
  { name: "Sudan", nativeName: "السودان", code: "+249", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg" },
  { name: "Suriname", nativeName: "Suriname", code: "+597", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg" },
  { name: "Sweden", nativeName: "Sverige", code: "+46", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg" },
  { name: "Switzerland", nativeName: "Schweiz", code: "+41", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg" },
  { name: "Syria", nativeName: "سوريا", code: "+963", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg" },
  { name: "Taiwan", nativeName: "台灣", code: "+886", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg" },
  { name: "Tajikistan", nativeName: "Тоҷикистон", code: "+992", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg" },
  { name: "Tanzania", nativeName: "Tanzania", code: "+255", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg" },
  { name: "Thailand", nativeName: "ประเทศไทย", code: "+66", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg" },
  { name: "Timor-Leste", nativeName: "Timor-Leste", code: "+670", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg" },
  { name: "Togo", nativeName: "Togo", code: "+228", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg" },
  { name: "Tonga", nativeName: "Tonga", code: "+676", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg" },
  { name: "Trinidad and Tobago", nativeName: "Trinidad and Tobago", code: "+1-868", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg" },
  { name: "Tunisia", nativeName: "تونس", code: "+216", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg" },
  { name: "Turkey", nativeName: "Türkiye", code: "+90", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg" },
  { name: "Turkmenistan", nativeName: "Türkmenistan", code: "+993", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg" },
  { name: "Tuvalu", nativeName: "Tuvalu", code: "+688", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg" },
  { name: "Uganda", nativeName: "Uganda", code: "+256", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg" },
  { name: "Ukraine", nativeName: "Україна", code: "+380", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg" },
  { name: "United Arab Emirates", nativeName: "الإمارات العربية المتحدة", code: "+971", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg" },
  { name: "United Kingdom", nativeName: "United Kingdom", code: "+44", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg" },
  { name: "United States", nativeName: "United States", code: "+1", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg" },
  { name: "Uruguay", nativeName: "Uruguay", code: "+598", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg" },
  { name: "Uzbekistan", nativeName: "O‘zbekiston", code: "+998", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg" },
  { name: "Vanuatu", nativeName: "Vanuatu", code: "+678", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg" },
  { name: "Vatican City", nativeName: "Città del Vaticano", code: "+379", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg" },
  { name: "Venezuela", nativeName: "Venezuela", code: "+58", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg" },
  { name: "Vietnam", nativeName: "Việt Nam", code: "+84", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg" },
  { name: "Yemen", nativeName: "اليمن", code: "+967", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg" },
  { name: "Zambia", nativeName: "Zambia", code: "+260", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg" },
  { name: "Zimbabwe", nativeName: "Zimbabwe", code: "+263", flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg" }
]
